#!/usr/bin/env python3
"""
Telemetry Flow Test

Tests the complete telemetry data flow:
OAS -> GSC -> MCWI

Validates that telemetry packets can be:
1. Generated by OAS types
2. Processed by GSC simulation
3. Consumed by MCWI format
"""

import sys
import json
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Any
from datetime import datetime, timezone


@dataclass
class TestResult:
    name: str
    passed: bool
    message: str
    data: dict | None = None


class TelemetryFlowTest:
    """Test telemetry data compatibility across segments."""
    
    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.results: list[TestResult] = []
    
    def run_all_tests(self) -> bool:
        """Run all telemetry flow tests."""
        print("=" * 60)
        print("  Telemetry Flow Integration Test")
        print("=" * 60)
        print()
        
        # Test 1: Create mock OAS telemetry packet
        self._test_oas_telemetry_generation()
        
        # Test 2: Validate GSC can process the packet
        self._test_gsc_telemetry_processing()
        
        # Test 3: Validate MCWI can consume the packet
        self._test_mcwi_telemetry_consumption()
        
        # Test 4: End-to-end transformation
        self._test_end_to_end_transformation()
        
        return self._print_results()
    
    def _create_mock_oas_packet(self) -> dict[str, Any]:
        """Create a mock telemetry packet in OAS format."""
        return {
            "ship_id": "SHIP-001",
            "timestamp_ms": int(datetime.now(timezone.utc).timestamp() * 1000),
            "mission_elapsed_ms": 3600000,  # 1 hour
            "kinematics": {
                "position": {"x": 6771.0, "y": 0.0, "z": 0.0},  # LEO
                "velocity": {"x": 0.0, "y": 7.67, "z": 0.0},     # Orbital velocity
                "orientation": {"w": 1.0, "x": 0.0, "y": 0.0, "z": 0.0},
                "angular_velocity": {"x": 0.0, "y": 0.0, "z": 0.001},
                "timestamp_ms": int(datetime.now(timezone.utc).timestamp() * 1000),
            },
            "resources": {
                "propellant_kg": 50000.0,
                "oxidizer_kg": 100000.0,
                "battery_charge": 0.95,
                "battery_temp_k": 293.0,
                "delta_v_remaining": 3.2,
            },
            "health": {
                "propulsion": 1,  # NOMINAL
                "navigation": 1,
                "communication": 1,
                "power": 1,
                "thermal": 1,
                "life_support": 1,
            },
        }
    
    def _transform_oas_to_gsc(self, oas_packet: dict) -> dict:
        """Transform OAS packet to GSC format."""
        return {
            "ship_id": oas_packet["ship_id"],
            "timestamp": datetime.fromtimestamp(
                oas_packet["timestamp_ms"] / 1000, 
                tz=timezone.utc
            ).isoformat(),
            "position": oas_packet["kinematics"]["position"],
            "velocity": oas_packet["kinematics"]["velocity"],
            "orientation": oas_packet["kinematics"]["orientation"],
            "propellant_kg": oas_packet["resources"]["propellant_kg"],
            "battery_percent": oas_packet["resources"]["battery_charge"] * 100,
            "health_status": "NOMINAL" if all(
                v == 1 for v in oas_packet["health"].values()
            ) else "DEGRADED",
        }
    
    def _transform_gsc_to_mcwi(self, gsc_packet: dict) -> dict:
        """Transform GSC packet to MCWI format."""
        return {
            "shipId": gsc_packet["ship_id"],
            "shipName": f"Starship {gsc_packet['ship_id'].split('-')[1]}",
            "position": {
                "frame": "EARTH",  # Determined by position
                "x": gsc_packet["position"]["x"],
                "y": gsc_packet["position"]["y"],
                "z": gsc_packet["position"]["z"],
            },
            "velocity": gsc_packet["velocity"],
            "orientation": gsc_packet["orientation"],
            "phase": 3,  # EARTH_ORBIT based on position
            "overallHealth": 1 if gsc_packet["health_status"] == "NOMINAL" else 2,
            "aiConfidence": 0.95,
            "currentObjective": "Parking orbit established",
            "lastUpdate": gsc_packet["timestamp"],
        }
    
    def _test_oas_telemetry_generation(self):
        """Test OAS can generate valid telemetry packets."""
        try:
            packet = self._create_mock_oas_packet()
            
            # Validate required fields
            required_fields = ["ship_id", "timestamp_ms", "kinematics", "resources", "health"]
            missing = [f for f in required_fields if f not in packet]
            
            if missing:
                self.results.append(TestResult(
                    name="OAS Telemetry Generation",
                    passed=False,
                    message=f"Missing required fields: {missing}",
                    data=packet,
                ))
            else:
                self.results.append(TestResult(
                    name="OAS Telemetry Generation",
                    passed=True,
                    message="Generated valid telemetry packet",
                    data=packet,
                ))
        except Exception as e:
            self.results.append(TestResult(
                name="OAS Telemetry Generation",
                passed=False,
                message=f"Exception: {str(e)}",
            ))
    
    def _test_gsc_telemetry_processing(self):
        """Test GSC can process OAS telemetry."""
        try:
            oas_packet = self._create_mock_oas_packet()
            gsc_packet = self._transform_oas_to_gsc(oas_packet)
            
            # Validate transformation preserved data
            if gsc_packet["ship_id"] != oas_packet["ship_id"]:
                self.results.append(TestResult(
                    name="GSC Telemetry Processing",
                    passed=False,
                    message="Ship ID mismatch after transformation",
                    data=gsc_packet,
                ))
            elif gsc_packet["position"] != oas_packet["kinematics"]["position"]:
                self.results.append(TestResult(
                    name="GSC Telemetry Processing",
                    passed=False,
                    message="Position data mismatch after transformation",
                    data=gsc_packet,
                ))
            else:
                self.results.append(TestResult(
                    name="GSC Telemetry Processing",
                    passed=True,
                    message="Transformed OAS packet to GSC format",
                    data=gsc_packet,
                ))
        except Exception as e:
            self.results.append(TestResult(
                name="GSC Telemetry Processing",
                passed=False,
                message=f"Exception: {str(e)}",
            ))
    
    def _test_mcwi_telemetry_consumption(self):
        """Test MCWI can consume GSC telemetry."""
        try:
            oas_packet = self._create_mock_oas_packet()
            gsc_packet = self._transform_oas_to_gsc(oas_packet)
            mcwi_packet = self._transform_gsc_to_mcwi(gsc_packet)
            
            # Validate MCWI format
            required_fields = ["shipId", "shipName", "position", "phase", "overallHealth"]
            missing = [f for f in required_fields if f not in mcwi_packet]
            
            if missing:
                self.results.append(TestResult(
                    name="MCWI Telemetry Consumption",
                    passed=False,
                    message=f"Missing required MCWI fields: {missing}",
                    data=mcwi_packet,
                ))
            elif mcwi_packet["shipId"] != oas_packet["ship_id"]:
                self.results.append(TestResult(
                    name="MCWI Telemetry Consumption",
                    passed=False,
                    message="Ship ID lost in transformation chain",
                    data=mcwi_packet,
                ))
            else:
                self.results.append(TestResult(
                    name="MCWI Telemetry Consumption",
                    passed=True,
                    message="Transformed GSC packet to MCWI format",
                    data=mcwi_packet,
                ))
        except Exception as e:
            self.results.append(TestResult(
                name="MCWI Telemetry Consumption",
                passed=False,
                message=f"Exception: {str(e)}",
            ))
    
    def _test_end_to_end_transformation(self):
        """Test complete OAS -> GSC -> MCWI transformation."""
        try:
            # Full pipeline
            oas_packet = self._create_mock_oas_packet()
            gsc_packet = self._transform_oas_to_gsc(oas_packet)
            mcwi_packet = self._transform_gsc_to_mcwi(gsc_packet)
            
            # Verify position data survives the entire chain
            original_x = oas_packet["kinematics"]["position"]["x"]
            final_x = mcwi_packet["position"]["x"]
            
            if abs(original_x - final_x) < 0.001:
                self.results.append(TestResult(
                    name="End-to-End Transformation",
                    passed=True,
                    message=f"Position data preserved: x={original_x} -> x={final_x}",
                    data={
                        "original": oas_packet["kinematics"]["position"],
                        "final": mcwi_packet["position"],
                    },
                ))
            else:
                self.results.append(TestResult(
                    name="End-to-End Transformation",
                    passed=False,
                    message=f"Position data corrupted: x={original_x} -> x={final_x}",
                    data={
                        "original": oas_packet["kinematics"]["position"],
                        "final": mcwi_packet["position"],
                    },
                ))
                
        except Exception as e:
            self.results.append(TestResult(
                name="End-to-End Transformation",
                passed=False,
                message=f"Exception: {str(e)}",
            ))
    
    def _print_results(self) -> bool:
        """Print test results and return success status."""
        print("\nTest Results:")
        print("-" * 60)
        
        all_passed = True
        for result in self.results:
            icon = "✓" if result.passed else "✗"
            color = "\033[92m" if result.passed else "\033[91m"
            reset = "\033[0m"
            
            print(f"{color}{icon}{reset} {result.name}")
            print(f"  {result.message}")
            
            if not result.passed:
                all_passed = False
        
        print("\n" + "=" * 60)
        if all_passed:
            print("\033[92m✓ All telemetry flow tests passed!\033[0m")
        else:
            print("\033[91m✗ Some telemetry flow tests failed!\033[0m")
        print("=" * 60 + "\n")
        
        return all_passed


def main():
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent
    
    test = TelemetryFlowTest(project_root)
    success = test.run_all_tests()
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
